// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaI-wTWbByEPWEDCrjH61Cr1dNyPpVK-4',
    appId: '1:374335092767:web:057d3f514c3b6fb45d7d2a',
    messagingSenderId: '374335092767',
    projectId: 'fruit-hub-d6f0b',
    authDomain: 'fruit-hub-d6f0b.firebaseapp.com',
    storageBucket: 'fruit-hub-d6f0b.firebasestorage.app',
    measurementId: 'G-S4GKPX4LV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdC_2zjQJ-bOA_OVbX4zfcbhn6waQtFDA',
    appId: '1:374335092767:android:2fc4951f5ddd6fbf5d7d2a',
    messagingSenderId: '374335092767',
    projectId: 'fruit-hub-d6f0b',
    storageBucket: 'fruit-hub-d6f0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGr43p5Z7hrz7jD8zA5tfVGlDvCKLq65E',
    appId: '1:374335092767:ios:fc7385e7138507fb5d7d2a',
    messagingSenderId: '374335092767',
    projectId: 'fruit-hub-d6f0b',
    storageBucket: 'fruit-hub-d6f0b.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGr43p5Z7hrz7jD8zA5tfVGlDvCKLq65E',
    appId: '1:374335092767:ios:fc7385e7138507fb5d7d2a',
    messagingSenderId: '374335092767',
    projectId: 'fruit-hub-d6f0b',
    storageBucket: 'fruit-hub-d6f0b.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaI-wTWbByEPWEDCrjH61Cr1dNyPpVK-4',
    appId: '1:374335092767:web:1d8136fe857937f45d7d2a',
    messagingSenderId: '374335092767',
    projectId: 'fruit-hub-d6f0b',
    authDomain: 'fruit-hub-d6f0b.firebaseapp.com',
    storageBucket: 'fruit-hub-d6f0b.firebasestorage.app',
    measurementId: 'G-0GG4KZRFYH',
  );
}
